type IActionTypes = {
  SET_PRODUCTS: string,
  SET_SELECTED_PRODUCT: string,
  CLEAR_SELECTED_PRODUCT: string,
}

export const ActionTypes: IActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',
  CLEAR_SELECTED_PRODUCT: 'CLEAR_SELECTED_PRODUCT',
}
